name: Publish release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  publish:
    name: Publish
    needs: [versions]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Validate publishing
        run: bun publish --dry-run && bunx jsr publish --dry-run
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to registries
        run: bun publish && bunx jsr publish
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
